version: "3.8"

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      # public URL settings (your custom ngrok domain)
      - N8N_HOST=${NGROK_CUST_DOMAIN}
      - N8N_PROTOCOL=https
      - N8N_WEBHOOK_URL=${NGROK_CUST_DOMAIN_URL}/
      - WEBHOOK_URL=${NGROK_CUST_DOMAIN_URL}
      - N8N_EDITOR_BASE_URL=${NGROK_CUST_DOMAIN_URL}
      # basic auth (optional)
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - NODE_ENV=production
    volumes:
      - ./n8n-data:/home/node/.n8n
    restart: unless-stopped

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    depends_on:
      - n8n
    volumes:
      - ./ngrok.yaml:/home/.config/ngrok/ngrok.yaml:ro
    # start all endpoints defined in your config
    entrypoint: ["ngrok", "start", "--all", "--config", "/home/.config/ngrok/ngrok.yaml"]
    restart: unless-stopped